/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ProAula.Hotel.Gui;

import ProAula.Hotel.Business.Huesped.Command.Delete.DeleteHuespedCommand;
import ProAula.Hotel.Business.Huesped.Command.Delete.DeleteHuespedCommandHandler;
import ProAula.Hotel.Business.Huesped.Command.Delete.IDeleteHuespedCommand;
import ProAula.Hotel.Business.Huesped.Queries.GetAll.GetAllHuespedQueryHandler;
import ProAula.Hotel.Business.Huesped.Queries.GetAll.IGetAllHuespedQuery;
import ProAula.Hotel.Domain.Model.Huesped;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DANIEL
 */
public class JFrameEliminarHuesped extends javax.swing.JFrame {
    
    // Lista que contendra los huespedes recuperados
    private List<Huesped> huespedesList;

    /**
     * Creates new form JFrameEliminarHuesped
     */
    public JFrameEliminarHuesped() {
        initComponents();
        listarHuespedes();
    }
    
    private void listarHuespedes() {
        try {
            IGetAllHuespedQuery query = new GetAllHuespedQueryHandler();
            huespedesList = query.handler();

            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);

            // formateador para la fecha de nacimiento
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");

            for (Huesped h : huespedesList) {
                String fecha = h.getFechaNacimientoHuesped() != null
                    ? sdf.format(h.getFechaNacimientoHuesped())
                    : "N/A";

                model.addRow(new Object[]{
                    h.getNombresHuesped(),
                    h.getApellidosHuesped(),
                    h.getIdentificacionHuespedAcompa(),
                    fecha,
                    h.getGeneroHuesped() != null 
                        ? h.getGeneroHuesped() 
                        : "N/A",
                    h.getEmailHuesped() != null 
                        ? h.getEmailHuesped() 
                        : "N/A"
                });
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(
                this,
                "Error al listar huéspedes: " + ex.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE
            );
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonEditarHuesped = new javax.swing.JButton();
        jButtonEliminarHuesped = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nombres", "Apellidos", "Identificacion", "Fecha Nacimiento", "Genero", "Email"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButtonEditarHuesped.setBackground(new java.awt.Color(102, 255, 102));
        jButtonEditarHuesped.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEditarHuesped.setText("Editar Huesped");
        jButtonEditarHuesped.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarHuespedActionPerformed(evt);
            }
        });

        jButtonEliminarHuesped.setBackground(new java.awt.Color(255, 51, 51));
        jButtonEliminarHuesped.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEliminarHuesped.setText("Eliminar Huesped");
        jButtonEliminarHuesped.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarHuespedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jButtonEditarHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 173, Short.MAX_VALUE)
                .addComponent(jButtonEliminarHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEditarHuesped)
                    .addComponent(jButtonEliminarHuesped))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEditarHuespedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarHuespedActionPerformed
        int fila = jTable1.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this,
                "Seleccione un huésped para editar.",
                "Atención",
                JOptionPane.WARNING_MESSAGE);
            return;
        }

        Huesped h = huespedesList.get(fila);

        JFrameEditarHuesped ventanaEditar = new JFrameEditarHuesped();

        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String fechaStr = h.getFechaNacimientoHuesped() != null
            ? sdf.format(h.getFechaNacimientoHuesped())
            : "";

        ventanaEditar.setDatosHuesped(
            h.getNombresHuesped(),
            h.getApellidosHuesped(),
            h.getIdentificacionHuespedAcompa(),
            fechaStr,
            h.getGeneroHuesped() != null ? h.getGeneroHuesped() : "",
            h.getEmailHuesped()  != null ? h.getEmailHuesped()  : ""
        );
        ventanaEditar.setHuespedId(h.getId());
        
        ventanaEditar.setLocationRelativeTo(this);
        ventanaEditar.setVisible(true);
    }//GEN-LAST:event_jButtonEditarHuespedActionPerformed

    private void jButtonEliminarHuespedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarHuespedActionPerformed
        try {
            int fila = jTable1.getSelectedRow();
            if (fila == -1) {
                JOptionPane.showMessageDialog(
                    this,
                    "Seleccione un huésped para eliminar.",
                    "Atención",
                    JOptionPane.WARNING_MESSAGE
                );
                return;
            }

            int confirm = JOptionPane.showConfirmDialog(
                this,
                "¿Estás seguro de que deseas eliminar este huésped?",
                "Confirmar eliminación",
                JOptionPane.YES_NO_OPTION
            );
            if (confirm != JOptionPane.YES_OPTION) {
                return;
            }

            Huesped h = huespedesList.get(fila);
            DeleteHuespedCommand command = new DeleteHuespedCommand(h.getId());
            IDeleteHuespedCommand handler = new DeleteHuespedCommandHandler();
            Huesped eliminado = handler.handler(command);

            JOptionPane.showMessageDialog(
                this,
                "Huésped eliminado correctamente:\n" +
                eliminado.getNombresHuesped() + " " + eliminado.getApellidosHuesped(),
                "Éxito",
                JOptionPane.INFORMATION_MESSAGE
            );
            listarHuespedes();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(
                this,
                "Error al eliminar el huésped: " + ex.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_jButtonEliminarHuespedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameEliminarHuesped.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameEliminarHuesped.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameEliminarHuesped.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameEliminarHuesped.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameEliminarHuesped().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEditarHuesped;
    private javax.swing.JButton jButtonEliminarHuesped;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
