/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ProAula.Hotel.Gui;

import ProAula.Hotel.Business.Reservas.Queries.GetAll.GetAllReservasQueryHandler;
import ProAula.Hotel.Business.Reservas.Queries.GetReservaByIdQueryHandler;
import ProAula.Hotel.Business.Reservas.Queries.GetReservaByIdRequestQuery;
import ProAula.Hotel.Domain.Model.Reservas;
import ProAula.Hotel.Domain.Model.Usuario;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DANIEL
 */
public class JFrameListar extends javax.swing.JFrame {

    /**
     * Creates new form PanelListar
     */
    public JFrameListar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtListarXId = new javax.swing.JTextField();
        jButtonBuscarXId = new javax.swing.JButton();
        jButtonListarTodos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        label1.setText("Listar Reservas");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Fecha Reserva", "Fecha llegada", "Fecha Salida", "Huespedes", "Habitaciones", "Nombres", "Apellidos", "Identificacion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jLabel1.setText("Buscar por ID:");

        jButtonBuscarXId.setText("Buscar");
        jButtonBuscarXId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarXIdActionPerformed(evt);
            }
        });

        jButtonListarTodos.setText("Listar Todos");
        jButtonListarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarTodosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtListarXId, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonBuscarXId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonListarTodos))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 656, Short.MAX_VALUE))
                .addGap(22, 22, 22))
            .addGroup(layout.createSequentialGroup()
                .addGap(258, 258, 258)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtListarXId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscarXId)
                    .addComponent(jButtonListarTodos))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBuscarXIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarXIdActionPerformed
        try {
            String textoId = txtListarXId.getText().trim();
            if (textoId.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Ingrese un ID de reserva.");
                return;
            }

            int id = Integer.parseInt(textoId);
            GetReservaByIdRequestQuery request = new GetReservaByIdRequestQuery(id);
            GetReservaByIdQueryHandler handler = new GetReservaByIdQueryHandler();
            Reservas reserva = handler.handler(request);

            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0); // Limpiar tabla

            SimpleDateFormat fmt = new SimpleDateFormat("yyyy-MM-dd");

            String fechaResFmt     = fmt.format(reserva.getFechaReserva());
            String fechaLlegFmt    = fmt.format(reserva.getFechaLlegada());
            String fechaSalidaFmt  = fmt.format(reserva.getFechaSalida());

            if (reserva.getUsuarios() != null && !reserva.getUsuarios().isEmpty()) {
                for (Usuario u : reserva.getUsuarios()) {
                    model.addRow(new Object[]{
                        fechaResFmt,
                        fechaLlegFmt,
                        fechaSalidaFmt,
                        String.valueOf(reserva.getHuespedes()),
                        String.valueOf(reserva.getHabitaciones()),
                        u.getNombres(),
                        u.getApellidos(),
                        u.getIdentificacion()
                    });
                }
            } else {
                model.addRow(new Object[]{
                    fechaResFmt,
                    fechaLlegFmt,
                    fechaSalidaFmt,
                    String.valueOf(reserva.getHuespedes()),
                    String.valueOf(reserva.getHabitaciones()),
                    "N/A", "N/A", "N/A"
                });
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El ID debe ser un numero.");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
        }
    }//GEN-LAST:event_jButtonBuscarXIdActionPerformed

    private void jButtonListarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarTodosActionPerformed
        try {
            // Inicializar el handler de la consulta
            GetAllReservasQueryHandler handler = new GetAllReservasQueryHandler();
            List<Reservas> reservas = handler.handler();

            // Modelo de la tabla
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0); // Limpiar tabla antes de agregar nuevos datos

            // Formateamos la fecha a AAAA-MM-DD
            SimpleDateFormat fmt = new SimpleDateFormat("yyyy-MM-dd");

            for (Reservas r : reservas) {
                // Formateamos una sola vez por reserva
                String fechaResFmt    = fmt.format(r.getFechaReserva());
                String fechaLlegFmt   = fmt.format(r.getFechaLlegada());
                String fechaSalidaFmt = fmt.format(r.getFechaSalida());

                List<Usuario> usuarios = r.getUsuarios();
                if (usuarios != null && !usuarios.isEmpty()) {
                    for (Usuario u : usuarios) {
                        model.addRow(new Object[]{
                            fechaResFmt,
                            fechaLlegFmt,
                            fechaSalidaFmt,
                            String.valueOf(r.getHuespedes()),
                            String.valueOf(r.getHabitaciones()),
                            u.getNombres(),
                            u.getApellidos(),
                            u.getIdentificacion()
                        });
                    }
                } else {
                    model.addRow(new Object[]{
                        fechaResFmt,
                        fechaLlegFmt,
                        fechaSalidaFmt,
                        String.valueOf(r.getHuespedes()),
                        String.valueOf(r.getHabitaciones()),
                        "N/A", // Nombres
                        "N/A", // Apellidos
                        "N/A"  // Identificación
                    });
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
        }
    }//GEN-LAST:event_jButtonListarTodosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameListar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameListar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameListar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameListar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameListar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscarXId;
    private javax.swing.JButton jButtonListarTodos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private java.awt.Label label1;
    private javax.swing.JTextField txtListarXId;
    // End of variables declaration//GEN-END:variables
}
