/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ProAula.Hotel.Gui;

import ProAula.Hotel.Business.Reservas.Command.DeleteHabitacionCommand;
import ProAula.Hotel.Business.Reservas.Command.DeleteHabitacionCommandHandler;
import ProAula.Hotel.Business.Reservas.Command.IDeleteHabitacionCommand;
import ProAula.Hotel.Business.Reservas.Queries.GetAllHabitacionesQueryHandler;
import ProAula.Hotel.Domain.Model.Habitaciones;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DANIEL
 */
public class JFrameEliminarHabitaciones extends javax.swing.JFrame {

    /**
     * Creates new form JFrameEliminarHabitaciones
     */
    public JFrameEliminarHabitaciones() {
        initComponents();
        listarHabitaciones();
    }
    
    private List<Habitaciones> habitacionesList = new ArrayList<>();
    
    private void listarHabitaciones() {
        try {
            GetAllHabitacionesQueryHandler handler = new GetAllHabitacionesQueryHandler();
            habitacionesList = handler.handler();

            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);

            for (Habitaciones h : habitacionesList) {
                model.addRow(new Object[]{
                    h.getNumeroHabitacion(),
                    h.getEstadoHabitacion(),
                    h.getIdentificacionHuesped() != null
                        ? h.getIdentificacionHuesped()
                        : "N/A"
                });
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,
                "Error al listar habitaciones: " + ex.getMessage());
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonEditarHabitacion = new javax.swing.JButton();
        jButtonEliminarHabitacion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Numero Habitacion", "Estado Habitacion", "Identificacion Huesped"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButtonEditarHabitacion.setBackground(new java.awt.Color(102, 255, 102));
        jButtonEditarHabitacion.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEditarHabitacion.setText("Editar Habitacion");
        jButtonEditarHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarHabitacionActionPerformed(evt);
            }
        });

        jButtonEliminarHabitacion.setBackground(new java.awt.Color(255, 51, 51));
        jButtonEliminarHabitacion.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEliminarHabitacion.setText("Eliminar Habitacion");
        jButtonEliminarHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarHabitacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jButtonEditarHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonEliminarHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEditarHabitacion)
                    .addComponent(jButtonEliminarHabitacion))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEditarHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarHabitacionActionPerformed
        int fila = jTable1.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione una habitación para editar.");
            return;
        }
        Habitaciones hab = habitacionesList.get(fila);
        JFrameEditarHabitacion ventanaEditar = new JFrameEditarHabitacion();
        ventanaEditar.setDatosHabitacion(
            String.valueOf(hab.getNumeroHabitacion()),
            hab.getEstadoHabitacion(),
            hab.getIdentificacionHuesped()
        );
        ventanaEditar.setHabitacionId(hab.getId());
        ventanaEditar.setLocationRelativeTo(this);
        ventanaEditar.setVisible(true);
    }//GEN-LAST:event_jButtonEditarHabitacionActionPerformed

    private void jButtonEliminarHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarHabitacionActionPerformed
        try {
            int fila = jTable1.getSelectedRow();
            if (fila == -1) {
                JOptionPane.showMessageDialog(this, "Seleccione una habitación para eliminar.");
                return;
            }

            int confirm = JOptionPane.showConfirmDialog(
                this,
                "¿Estás seguro de que deseas eliminar esta habitación?",
                "Confirmar eliminación",
                JOptionPane.YES_NO_OPTION
            );
            if (confirm != JOptionPane.YES_OPTION) {
                return;
            }

            Habitaciones h = habitacionesList.get(fila);
            DeleteHabitacionCommand command = new DeleteHabitacionCommand(h.getId());
            IDeleteHabitacionCommand handler = new DeleteHabitacionCommandHandler();
            handler.handler(command);

            JOptionPane.showMessageDialog(this, "Habitación eliminada correctamente.");
            listarHabitaciones();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al eliminar la habitación: " + ex.getMessage());
        }
    }//GEN-LAST:event_jButtonEliminarHabitacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameEliminarHabitaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameEliminarHabitaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameEliminarHabitaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameEliminarHabitaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameEliminarHabitaciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEditarHabitacion;
    private javax.swing.JButton jButtonEliminarHabitacion;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
