/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ProAula.Hotel.Gui;

import ProAula.Hotel.Business.Reservas.Command.Create.CreateReservaCommand;
import ProAula.Hotel.Business.Reservas.Command.Create.CreateReservaCommandHandler;
import ProAula.Hotel.Business.Reservas.Command.Create.ICreateReservaCommand;
import ProAula.Hotel.Domain.Model.Reservas;
import ProAula.Hotel.Domain.Model.Usuario;
import ProAula.Hotel.Gui.JFrameListar;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JFormattedTextField;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import javax.swing.text.DateFormatter;
import javax.swing.text.DefaultFormatterFactory;

/**
 *
 * @author DANIEL
 */
public class PantallaPrincipal extends javax.swing.JFrame {
    
    private javax.swing.JTabbedPane tabbedPane;
    
    private final SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
    
    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal() {
        initComponents();
        configurarListeners();

        jMenuItemListar.addActionListener(e -> {
            JFrameListar ventana = new JFrameListar();
            ventana.setLocationRelativeTo(this); //Centrar la ventana sobre la principal
            ventana.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            ventana.setVisible(true);
        });
        
        jMenuItemEditar.addActionListener(e -> {
            JFrameEliminar ventana = new JFrameEliminar();
            ventana.setLocationRelativeTo(this);
            ventana.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            ventana.setVisible(true);
        });
        
        jMenuItemSalir.addActionListener(e -> {
            System.exit(0);
        });
        
        //Menu habitaciones
        jMenuItemListarHabitaciones.addActionListener(e -> {
            JFrameListarHabitaciones ventana = new JFrameListarHabitaciones();
            ventana.setLocationRelativeTo(this); //Centrar la ventana sobre la principal
            ventana.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            ventana.setVisible(true);
        });
        
        jMenuItemAgregarHabitaciones.addActionListener(e -> {
            JFrameCrearHabitacion ventana = new JFrameCrearHabitacion();
            ventana.setLocationRelativeTo(this);
            ventana.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            ventana.setVisible(true);
        });
        
        jMenuItemEditarHabitaciones.addActionListener(e -> {
            JFrameEliminarHabitaciones ventana = new JFrameEliminarHabitaciones();
            ventana.setLocationRelativeTo(this);
            ventana.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            ventana.setVisible(true);
        });
        
        //Menu huesped
        jMenuItemListarHuesped.addActionListener(e -> {
            JFrameListarHuesped ventana = new JFrameListarHuesped();
            ventana.setLocationRelativeTo(this); //Centrar la ventana sobre la principal
            ventana.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            ventana.setVisible(true);
        });      
        
        jMenuItemAgregarHuesped.addActionListener(e -> {
            JFrameCrearHuesped ventana = new JFrameCrearHuesped();
            ventana.setLocationRelativeTo(this);
            ventana.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            ventana.setVisible(true);
        });
        
        jMenuItemEditarHuesped.addActionListener(e -> {
            JFrameEliminarHuesped ventana = new JFrameEliminarHuesped();
            ventana.setLocationRelativeTo(this);
            ventana.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            ventana.setVisible(true);
        });  

    }
    
    private void configurarListeners() {
        // Registrar el listener del botón Agregar
        jButtonAgregar.addActionListener(this::jButtonAgregarActionPerformed);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        txtFechaReserva = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtFechaLlegada = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtFechaSalida = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jSpinnerHuespedes = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jSpinnerHabitaciones = new javax.swing.JSpinner();
        jButtonAgregar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtIdentificacion = new javax.swing.JTextField();
        label1 = new java.awt.Label();
        MenuPrincipal = new javax.swing.JMenuBar();
        jMenuPrincipal = new javax.swing.JMenu();
        jMenuItemListar = new javax.swing.JMenuItem();
        jMenuItemAgregar = new javax.swing.JMenuItem();
        jMenuItemEditar = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemSalir = new javax.swing.JMenuItem();
        jMenuHabitaciones = new javax.swing.JMenu();
        jMenuItemListarHabitaciones = new javax.swing.JMenuItem();
        jMenuItemAgregarHabitaciones = new javax.swing.JMenuItem();
        jMenuItemEditarHabitaciones = new javax.swing.JMenuItem();
        jMenuHuesped = new javax.swing.JMenu();
        jMenuItemListarHuesped = new javax.swing.JMenuItem();
        jMenuItemAgregarHuesped = new javax.swing.JMenuItem();
        jMenuItemEditarHuesped = new javax.swing.JMenuItem();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Fecha Reserva:");

        jLabel2.setText("Fecha llegada:");

        jLabel3.setText("Fecha Salida:");

        jLabel4.setText("Huespedes:");

        jLabel5.setText("Habitaciones:");

        jButtonAgregar.setText("Agregar");
        jButtonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarActionPerformed(evt);
            }
        });

        jLabel6.setText("Nombres:");

        jLabel7.setText("Apellidos:");

        jLabel8.setText("Identificacion:");

        label1.setText("Ingresar fecha Año-Mes-Dia");

        jMenuPrincipal.setText("Menu");

        jMenuItemListar.setText("Listar");
        jMenuPrincipal.add(jMenuItemListar);

        jMenuItemAgregar.setText("Agregar");
        jMenuPrincipal.add(jMenuItemAgregar);

        jMenuItemEditar.setText("Editar / Eliminar");
        jMenuPrincipal.add(jMenuItemEditar);
        jMenuPrincipal.add(jSeparator1);

        jMenuItemSalir.setText("Salir");
        jMenuPrincipal.add(jMenuItemSalir);

        MenuPrincipal.add(jMenuPrincipal);

        jMenuHabitaciones.setText("MenuHabitaciones");

        jMenuItemListarHabitaciones.setText("Listar Habitaciones");
        jMenuHabitaciones.add(jMenuItemListarHabitaciones);

        jMenuItemAgregarHabitaciones.setText("Agregar Habitaciones");
        jMenuHabitaciones.add(jMenuItemAgregarHabitaciones);

        jMenuItemEditarHabitaciones.setText("Editar / Eliminar Habitaciones");
        jMenuHabitaciones.add(jMenuItemEditarHabitaciones);

        MenuPrincipal.add(jMenuHabitaciones);

        jMenuHuesped.setText("Menu Huesped");

        jMenuItemListarHuesped.setText("Listar Huesped");
        jMenuHuesped.add(jMenuItemListarHuesped);

        jMenuItemAgregarHuesped.setText("Agregar Huesped");
        jMenuHuesped.add(jMenuItemAgregarHuesped);

        jMenuItemEditarHuesped.setText("Editar / Eliminar Huesped");
        jMenuHuesped.add(jMenuItemEditarHuesped);

        MenuPrincipal.add(jMenuHuesped);

        setJMenuBar(MenuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtIdentificacion)
                    .addComponent(txtApellidos)
                    .addComponent(txtNombres)
                    .addComponent(txtFechaLlegada)
                    .addComponent(txtFechaReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFechaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerHabitaciones)
                    .addComponent(jSpinnerHuespedes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
            .addGroup(layout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(jButtonAgregar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtFechaReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtFechaLlegada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtFechaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jSpinnerHuespedes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jSpinnerHabitaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jButtonAgregar)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void jButtonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarActionPerformed
        // 1) Parsear las fechas y validar
        Date fechaReserva;
        Date fechaLlegada;
        Date fechaSalida;
        
        try {
            fechaReserva = df.parse(txtFechaReserva.getText().trim());
            fechaLlegada = df.parse(txtFechaLlegada.getText().trim());
            fechaSalida  = df.parse(txtFechaSalida.getText().trim());
        } catch (java.text.ParseException pe) {
            return;
        }
        
        // Validar que la fechaLlegada no sea mayor a la fechaSalida
        if (fechaLlegada.after(fechaSalida)) {
            JOptionPane.showMessageDialog(this,
                "La fecha de llegada (" + df.format(fechaLlegada) + 
                ") no puede ser superior a la fecha de salida (" + df.format(fechaSalida) + ").",
                "Error de Fechas",
                JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validar que fechaReserva no sea mayor a la fechaLlegada
        if (fechaReserva.after(fechaLlegada)) {
            JOptionPane.showMessageDialog(this,
                "La fecha de reserva (" + df.format(fechaReserva) + 
                ") no puede ser superior a la fecha de llegada (" + df.format(fechaLlegada) + ").",
                "Error de Fechas",
                JOptionPane.ERROR_MESSAGE);
            return;
        }

        // 2) Leer los valores de los spinners
        int huespedes     = (Integer) jSpinnerHuespedes.getValue();
        int habitaciones = (Integer) jSpinnerHabitaciones.getValue();

        // 3) Construir la lista de usuarios
        List<Usuario> usuarios = new ArrayList<>();
        usuarios.add(new Usuario(
            txtNombres.getText().trim(),
            txtApellidos.getText().trim(),
            txtIdentificacion.getText().trim()
        ));

        // 4) Crear el comando y ejecutar el handler (este try es para errores del handler)
        try {
            CreateReservaCommand command = new CreateReservaCommand(
                fechaReserva,
                fechaLlegada,
                fechaSalida,
                huespedes,
                habitaciones,
                usuarios
            );
            ICreateReservaCommand handler = new CreateReservaCommandHandler();
            Reservas nuevaReserva = handler.handler(command);

            // 5) Informar al usuario y limpiar campos
            JOptionPane.showMessageDialog(this,
                "Reserva creada con ID: " + nuevaReserva.getId(),
                "Éxito",
                JOptionPane.INFORMATION_MESSAGE
            );
            limpiarFormulario();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,
                "Error al crear la reserva: " + ex.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_jButtonAgregarActionPerformed
    
    private void limpiarFormulario() {
        txtFechaReserva.setText("");
        txtFechaLlegada.setText("");
        txtFechaSalida.setText("");
        jSpinnerHuespedes.setValue(1);
        jSpinnerHabitaciones.setValue(1);
        txtNombres.setText("");
        txtApellidos.setText("");
        txtIdentificacion.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar MenuPrincipal;
    private javax.swing.JButton jButtonAgregar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenuHabitaciones;
    private javax.swing.JMenu jMenuHuesped;
    private javax.swing.JMenuItem jMenuItemAgregar;
    private javax.swing.JMenuItem jMenuItemAgregarHabitaciones;
    private javax.swing.JMenuItem jMenuItemAgregarHuesped;
    private javax.swing.JMenuItem jMenuItemEditar;
    private javax.swing.JMenuItem jMenuItemEditarHabitaciones;
    private javax.swing.JMenuItem jMenuItemEditarHuesped;
    private javax.swing.JMenuItem jMenuItemListar;
    private javax.swing.JMenuItem jMenuItemListarHabitaciones;
    private javax.swing.JMenuItem jMenuItemListarHuesped;
    private javax.swing.JMenuItem jMenuItemSalir;
    private javax.swing.JMenu jMenuPrincipal;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JSpinner jSpinnerHabitaciones;
    private javax.swing.JSpinner jSpinnerHuespedes;
    private java.awt.Label label1;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtFechaLlegada;
    private javax.swing.JTextField txtFechaReserva;
    private javax.swing.JTextField txtFechaSalida;
    private javax.swing.JTextField txtIdentificacion;
    private javax.swing.JTextField txtNombres;
    // End of variables declaration//GEN-END:variables
}
